name: Mirror Repository to Public Docs

on:
  push:
    branches:
      - gh-pages
      - mirrorRepository # Remove this after testing
  workflow_dispatch:  # Manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Mirror to Destination Repository
        run: |
          git config --global user.name 'sa_github_engagement'
          git config --global user.email 'sa_github_engagement@thehutgroup.com'
          git clone https://${{ secrets.SA_REPO_ACCESS_TOKEN }}@github.com/TheHutGroup/Horizon-Public-Docs.git
          git remote add destination https://sa_github_engagement:${{ secrets.SA_REPO_ACCESS_TOKEN }}@github.com/TheHutGroup/Horizon-Public-Docs.git
          git push --mirror destination